### ISSUE TITLE
OnAirBlock cover on mobile/smaller viewports

### ISSUE THREAD

**Issue by brudil** [urfonline/frontend#62]

**Comment by brudil** [comment]
@finevans It's because we have been hiding the image on mobile until now.

Shall we continue to hide the on air show's cover on mobile?

**Comment by finevans** [comment]
I actually think it looks good with the cover on mobile! Shall we keep it?

Sent from my iPhone

On 13 Feb 2018, at 12:31, James Canning <notifications@github.com<mailto:notifications@github.com>> wrote:


@finevans<https://github.com/finevans> It's because we have been hiding the image on mobile until now.

Shall we continue to hide the on air show's cover on mobile?

**Comment by brudil** [comment]
Sure. I'll let the image actually display then!
